spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5433/payments?options=-c%20timezone=UTC}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
razorpay:
  key:
    id: ${RAZORPAY_KEY_ID}
    secret: ${RAZORPAY_KEY_SECRET}
  webhook:
    secret: ${RAZORPAY_WEBHOOK_SECRET}